#!/usr/bin/env python3
"""Assemble build/body.tex from meta/works.yaml and the per-work files.

Reads works.yaml, sorts chronologically, and emits a sequence of \\input
directives for every work whose translation file exists. Speeches, rhetorical,
philosophical, and poetic works are wrapped in \\begin{cicerowork}; letters
are wrapped in \\begin{ciceroletter}.

Works without a translation file are skipped silently unless --include-pending
is passed, in which case a \\ciceropending{id}{title} placeholder is emitted.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("PyYAML required: pip install pyyaml\n")
    raise

REPO = Path(__file__).resolve().parent.parent
WORKS_YAML = REPO / "meta" / "works.yaml"
BODY_TEX = REPO / "build" / "body.tex"


def parse_date(s: str) -> tuple[int, int, int]:
    if s.startswith("-"):
        ys, rest = s[1:].split("-", 1)
        year = -int(ys)
    else:
        ys, rest = s.split("-", 1)
        year = int(ys)
    m, d = rest.split("-")
    return year, int(m), int(d)


def chronological_key(w: dict) -> tuple[int, int, int, str]:
    y, m, d = parse_date(w["date"])
    return (y, m, d, w["id"])


def short_year(work: dict) -> str:
    y, _, _ = parse_date(work["date"])
    era = "BC" if y < 0 else "AD"
    return f"{abs(y)} {era}"


_TEX_REPLACEMENTS = {
    "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
    "_": r"\_", "{": r"\{", "}": r"\}",
    "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    "\\": r"\textbackslash{}",
}


def tex_escape(s: str) -> str:
    return "".join(_TEX_REPLACEMENTS.get(c, c) for c in s)


def has_translation(work: dict) -> bool:
    return (REPO / work["english_file"]).exists()


def emit_block(work: dict) -> str:
    title = tex_escape(work["title_english"])
    title_latin = tex_escape(work["title_latin"])
    year_label = tex_escape(short_year(work))
    headnote_path = work["headnote_file"]
    english_path = work["english_file"]
    work_id = tex_escape(work["id"])
    env = "ciceroletter" if work["category"] == "letters" else "cicerowork"

    lines = [
        f"% --- {work['id']} -----------------------------------------------",
        f"\\begin{{{env}}}{{{work_id}}}{{{title}}}{{{title_latin}}}{{{year_label}}}",
    ]
    headnote_full = REPO / headnote_path
    if headnote_full.exists():
        lines.append(f"  \\input{{../{headnote_path}}}")
    lines.append(f"  \\input{{../{english_path}}}")
    lines.append(f"\\end{{{env}}}")
    lines.append("")
    return "\n".join(lines)


def emit_pending(work: dict) -> str:
    title = tex_escape(work["title_english"])
    work_id = tex_escape(work["id"])
    return (
        f"% --- {work['id']} (pending) ----------------------------------\n"
        f"\\ciceropending{{{work_id}}}{{{title}}}\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Assemble build/body.tex from works.yaml")
    parser.add_argument(
        "--include-pending",
        action="store_true",
        help="Emit placeholder entries for works without a translation file.",
    )
    args = parser.parse_args(argv)

    if not WORKS_YAML.exists():
        sys.stderr.write(f"meta/works.yaml not found at {WORKS_YAML}\n")
        return 2

    works = yaml.safe_load(WORKS_YAML.read_text(encoding="utf-8")) or []
    works.sort(key=chronological_key)

    out: list[str] = []
    out.append("% body.tex — generated by scripts/assemble_book.py")
    out.append("% Do not edit by hand. Edit meta/works.yaml or the per-work files.")
    out.append("")

    included = 0
    pending = 0
    for w in works:
        if has_translation(w):
            out.append(emit_block(w))
            included += 1
        elif args.include_pending:
            out.append(emit_pending(w))
            pending += 1

    BODY_TEX.parent.mkdir(parents=True, exist_ok=True)
    BODY_TEX.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(
        f"Wrote {BODY_TEX.relative_to(REPO)}: "
        f"{included} translated work(s)"
        + (f", {pending} pending placeholder(s)" if args.include_pending else "")
        + f" of {len(works)} total"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
