#!/usr/bin/env python3
"""Generate MANIFEST.md and build/chronology.tex from meta/works.yaml.

MANIFEST.md is the human-readable chronological table of contents,
sorted by date. build/chronology.tex is the LaTeX timeline / front-matter
TOC included by build/cicero.tex.

Run after editing works.yaml to regenerate both artefacts deterministically.
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("PyYAML required: pip install pyyaml\n")
    raise

REPO = Path(__file__).resolve().parent.parent
WORKS_YAML = REPO / "meta" / "works.yaml"
MANIFEST_MD = REPO / "MANIFEST.md"
CHRONOLOGY_TEX = REPO / "build" / "chronology.tex"


# ---------------------------------------------------------------------------
# Date helpers
# ---------------------------------------------------------------------------

MONTH_NAMES = [
    "", "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]


def parse_date(s: str) -> tuple[int, int, int]:
    """Parse an ISO-like date with negative year for BC.

    Returns (year, month, day). Year is signed (negative for BC).
    """
    if s.startswith("-"):
        year_s, rest = s[1:].split("-", 1)
        year = -int(year_s)
    else:
        year_s, rest = s.split("-", 1)
        year = int(year_s)
    m, d = rest.split("-")
    return year, int(m), int(d)


def chronological_key(w: dict) -> tuple[int, int, int, str]:
    y, m, d = parse_date(w["date"])
    return (y, m, d, w["id"])


def render_date(work: dict) -> str:
    """Human-readable date string for one entry."""
    y, m, d = parse_date(work["date"])
    era = "BC" if y < 0 else "AD"
    yr = abs(y)
    precision = work.get("date_precision", "year")
    if precision == "day":
        return f"{d} {MONTH_NAMES[m]} {yr} {era}"
    if precision == "month":
        return f"{MONTH_NAMES[m]} {yr} {era}"
    if precision == "year_range":
        end = work.get("date_range_end")
        if end:
            ey, _, _ = parse_date(end)
            ey_abs = abs(ey)
            if (ey < 0) == (y < 0):
                return f"{yr}-{ey_abs} {era}"
            return f"{yr} BC - {abs(ey)} AD"
        return f"c. {yr} {era}"
    return f"{yr} {era}"


def short_year(work: dict) -> str:
    """Compact year label for running heads / chronology rows."""
    y, _, _ = parse_date(work["date"])
    era = "BC" if y < 0 else "AD"
    return f"{abs(y)} {era}"


# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------

def render_manifest_md(works: list[dict]) -> str:
    lines: list[str] = []
    lines.append("# Manifest")
    lines.append("")
    lines.append(
        "Chronological master index of every work in `cicero-by-claude`. "
        "Auto-generated by `scripts/build_manifest.py` from `meta/works.yaml`. "
        "Do not edit by hand — edit the YAML and regenerate."
    )
    lines.append("")

    by_cat: dict[str, int] = {}
    by_status: dict[str, int] = {}
    for w in works:
        by_cat[w["category"]] = by_cat.get(w["category"], 0) + 1
        by_status[w.get("status", "pending")] = by_status.get(w.get("status", "pending"), 0) + 1

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Total works: **{len(works)}**")
    for cat in sorted(by_cat):
        lines.append(f"- {cat}: {by_cat[cat]}")
    lines.append("")
    lines.append("Status:")
    for st in ("final", "reviewed", "drafted", "pending"):
        if st in by_status:
            lines.append(f"- {st}: {by_status[st]}")
    lines.append("")

    lines.append("## Chronological order")
    lines.append("")
    lines.append("| # | Date | Category | Title | Status |")
    lines.append("|---|------|----------|-------|--------|")
    for i, w in enumerate(works, start=1):
        date = render_date(w)
        title = w["title_english"]
        cat = w["category"]
        status = w.get("status", "pending")
        lines.append(f"| {i} | {date} | {cat} | {title} | {status} |")
    lines.append("")

    return "\n".join(lines) + "\n"


def render_chronology_tex(works: list[dict]) -> str:
    """LaTeX-side chronology — emitted as a sectioned list of works grouped
    by year. Used as the TOC / timeline page in the assembled book.
    """
    lines: list[str] = []
    lines.append("% chronology.tex — generated by scripts/build_manifest.py")
    lines.append("% Do not edit by hand.")
    lines.append("")
    lines.append("\\chapter*{Chronology}")
    lines.append("\\addcontentsline{toc}{chapter}{Chronology}")
    lines.append("\\markboth{Chronology}{Chronology}")
    lines.append("")
    lines.append("\\begin{description}\\itemsep=0.25em")

    last_year: int | None = None
    for w in works:
        y, _, _ = parse_date(w["date"])
        if y != last_year:
            era = "BC" if y < 0 else "AD"
            lines.append(f"  \\item[\\textsc{{{abs(y)} {era}}}]\\hfill\\\\")
            last_year = y
        title = tex_escape(w["title_english"])
        date = tex_escape(render_date(w))
        lines.append(f"    \\textit{{{title}}} \\dotfill\\ {date}\\\\")

    lines.append("\\end{description}")
    lines.append("")
    return "\n".join(lines) + "\n"


_TEX_REPLACEMENTS = {
    "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
    "_": r"\_", "{": r"\{", "}": r"\}",
    "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    "\\": r"\textbackslash{}",
}


def tex_escape(s: str) -> str:
    out = []
    for c in s:
        out.append(_TEX_REPLACEMENTS.get(c, c))
    return "".join(out)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def main() -> int:
    if not WORKS_YAML.exists():
        sys.stderr.write(f"meta/works.yaml not found at {WORKS_YAML}\n")
        return 2

    works = yaml.safe_load(WORKS_YAML.read_text(encoding="utf-8")) or []
    works.sort(key=chronological_key)

    md = render_manifest_md(works)
    MANIFEST_MD.write_text(md, encoding="utf-8")
    print(f"Wrote {MANIFEST_MD.relative_to(REPO)} ({len(works)} entries)")

    CHRONOLOGY_TEX.parent.mkdir(parents=True, exist_ok=True)
    tex = render_chronology_tex(works)
    CHRONOLOGY_TEX.write_text(tex, encoding="utf-8")
    print(f"Wrote {CHRONOLOGY_TEX.relative_to(REPO)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
