#!/usr/bin/env bash
# cowork_handoff.sh — one command to land a Cowork translation session.
#
# Cowork (Claude in Anthropic's desktop app) cannot push to origin from its
# sandbox and cannot delete files. So after each Cowork session has done its
# translation work, you run this script on your laptop to:
#
#   1. Clean up any stale .git/index.lock left by Cowork's git status calls
#   2. Remove the placeholder stub on 054bc-ad-familiares-13-49.tex if present
#      (an artifact of a one-off fetch debugging session — harmless if absent)
#   3. Stage every change Cowork made
#   4. Commit with a descriptive message
#   5. Push to origin/main
#
# Usage:
#   bash scripts/cowork_handoff.sh "session N: brief description"
#
# Examples:
#   bash scripts/cowork_handoff.sh "session 1: +22 letters (autumn 54 BC through April 53 BC)"
#   bash scripts/cowork_handoff.sh "session 7: entity stub enrichment, 50 entries"
#
# Idempotent: if there's nothing to commit, the script exits cleanly without
# pushing an empty commit.
set -euo pipefail

cd "$(dirname "$0")/.."

if [ $# -lt 1 ]; then
  echo "Usage: bash scripts/cowork_handoff.sh \"session N: description\"" >&2
  exit 2
fi

LABEL="$1"

echo "--- 1. cleanup stuck locks / cowork artifacts ---"
rm -f .git/index.lock 2>/dev/null || true
# The placeholder stub from session-1's failed Fam 13.49 fetch test.
# Harmless if already gone.
if [ -f latin/letters/054bc-ad-familiares-13-49.tex ]; then
  if head -2 latin/letters/054bc-ad-familiares-13-49.tex 2>/dev/null | grep -q "PLACEHOLDER"; then
    echo "  removing placeholder stub on latin/letters/054bc-ad-familiares-13-49.tex"
    git clean -f latin/letters/054bc-ad-familiares-13-49.tex 2>/dev/null || rm -f latin/letters/054bc-ad-familiares-13-49.tex
  fi
fi

echo "--- 2. stage all changes ---"
git add -A

if git diff --cached --quiet; then
  echo "Nothing staged. Working tree clean. Nothing to commit."
  exit 0
fi

# Brief preview of what's being landed.
echo "--- 3. summary of staged changes ---"
git diff --cached --stat | tail -20
echo

echo "--- 4. commit ---"
git -c user.name="Claude Cowork" -c user.email="cowork@anthropic.com" commit -m "Cowork ${LABEL}

Generated end-to-end by Claude Cowork (Anthropic's desktop agent product)
running as PM-Claude per CLAUDE.md. Per-letter translations and headnotes
were drafted by parallel worker sub-agents, sidecars regenerated by
scripts/backfill_structural.py, manifest by scripts/build_manifest.py.
Translator-notes and known cruxes documented in PROGRESS.md.

Co-Authored-By: Claude <noreply@anthropic.com>"

echo
echo "--- 5. push origin main ---"
git push origin main

echo
echo "✓ Cowork ${LABEL} landed on origin/main."
