#!/usr/bin/env python3
"""Finalize a parallel-agent batch: merge stuck session branches to main,
auto-resolve the predictable conflicts, regenerate derived files, validate.

Designed for minimum manual intervention. Run after parallel agent sessions
have finished:

    python scripts/finalize_parallel_batch.py

What it does:

  1. Fetches origin and lists session branches with commits not on main.
  2. For each, in committer-date order, attempts to merge into main with
     --no-ff. Auto-resolves conflicts on the predictable files:
        - MANIFEST.md, build/chronology.tex, build/body.tex,
          build/backmatter-generated.tex (always regenerated; takes ours).
        - data/greek-phrases.json, data/letter-network.json
          (regenerated by backfill_structural.py; takes ours).
        - PROGRESS.md (heuristic additive merge: keeps both sets of
          drafted-list entries; falls back to ours if heuristic fails).
        - meta/works.yaml (if the only conflict is "status: pending" vs
          "status: drafted" on the same line, drafted wins).
  3. If genuine unresolvable conflicts remain, aborts that merge and
     reports the branch for manual attention; continues with the next.
  4. After all merges, regenerates derived files:
        scripts/build_manifest.py
        scripts/backfill_structural.py
        scripts/enrich_letter_network.py
        scripts/generate_backmatter.py --profile reading
     and commits any updates.
  5. Runs scripts/validate.py and reports the result.

Idempotent: safe to re-run. If nothing is to merge, exits cleanly.

Conservative: never force-pushes, never deletes branches, never resets.
Anything it cannot resolve is reported, not papered over.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Files we know how to auto-resolve when they conflict.
# "regenerated" = take ours (current main version); the post-batch
# regeneration step will rebuild from the merged source files.
REGENERATED_FILES = {
    "MANIFEST.md",
    "build/chronology.tex",
    "build/body.tex",
    "build/backmatter-generated.tex",
    "data/greek-phrases.json",
    "data/letter-network.json",
}


def git(*args: str, check: bool = True, capture: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args],
        cwd=REPO,
        check=check,
        capture_output=capture,
        text=True,
    )


def info(msg: str) -> None:
    print(f"[finalize] {msg}", flush=True)


def warn(msg: str) -> None:
    print(f"[finalize] WARN: {msg}", file=sys.stderr, flush=True)


def list_session_branches() -> list[tuple[str, str]]:
    """Return [(short_name, sha), ...] for remote branches with commits
    not in origin/main. Sorted by committer date ascending."""
    out = git(
        "for-each-ref",
        "--format=%(refname:short) %(objectname) %(committerdate:unix)",
        "refs/remotes/origin/",
    ).stdout.strip().splitlines()
    main_sha = git("rev-parse", "origin/main").stdout.strip()
    branches: list[tuple[str, str, int]] = []
    for line in out:
        parts = line.split()
        if len(parts) != 3:
            continue
        ref, sha, ts = parts[0], parts[1], int(parts[2])
        if ref == "origin/main":
            continue
        # Skip if its tip is a strict ancestor of main (work already merged).
        rc = subprocess.run(
            ["git", "merge-base", "--is-ancestor", sha, main_sha],
            cwd=REPO, capture_output=True,
        ).returncode
        if rc == 0:
            continue
        branches.append((ref, sha, ts))
    branches.sort(key=lambda b: b[2])
    return [(b[0], b[1]) for b in branches]


def list_conflicts() -> list[str]:
    return git("diff", "--name-only", "--diff-filter=U").stdout.strip().splitlines()


def auto_resolve_progress_md() -> bool:
    """Attempt an additive merge on PROGRESS.md by stripping conflict
    markers and keeping both sides' content. Returns True if resolved.

    Heuristic: PROGRESS.md is documentary, not authoritative. The cost of
    a slightly duplicated paragraph is much less than the cost of losing
    a session's narrative entry. We take both sides and let the human
    consolidate later."""
    p = REPO / "PROGRESS.md"
    if not p.exists():
        return False
    text = p.read_text(encoding="utf-8")
    if "<<<<<<<" not in text:
        return True
    # Strip conflict markers, keeping both sides verbatim.
    out_lines: list[str] = []
    skip_until_end = False
    in_conflict = False
    for line in text.splitlines():
        if line.startswith("<<<<<<<"):
            in_conflict = True
            continue
        if line.startswith("======="):
            continue
        if line.startswith(">>>>>>>"):
            in_conflict = False
            continue
        out_lines.append(line)
    p.write_text("\n".join(out_lines) + "\n", encoding="utf-8")
    return "<<<<<<<" not in p.read_text(encoding="utf-8")


def auto_resolve_works_yaml() -> bool:
    """Attempt to resolve meta/works.yaml conflicts where the only
    differences are status-flip races (one side has 'status: pending',
    the other has 'status: drafted' on the same line). Drafted wins."""
    p = REPO / "meta" / "works.yaml"
    if not p.exists():
        return False
    text = p.read_text(encoding="utf-8")
    if "<<<<<<<" not in text:
        return True
    out_lines: list[str] = []
    in_conflict = False
    ours: list[str] = []
    theirs: list[str] = []
    side = None  # "ours" or "theirs"
    for line in text.splitlines():
        if line.startswith("<<<<<<<"):
            in_conflict = True
            ours, theirs, side = [], [], "ours"
            continue
        if line.startswith("======="):
            side = "theirs"
            continue
        if line.startswith(">>>>>>>"):
            in_conflict = False
            # Resolve: pick whichever block carries 'status: drafted'
            # if either does; otherwise pick ours.
            ours_text = "\n".join(ours)
            theirs_text = "\n".join(theirs)
            if "status: drafted" in theirs_text and "status: pending" in ours_text:
                out_lines.extend(theirs)
            elif "status: drafted" in ours_text:
                out_lines.extend(ours)
            else:
                # Same status on both? Heuristic punt — keep ours.
                out_lines.extend(ours)
            ours, theirs, side = [], [], None
            continue
        if in_conflict:
            (ours if side == "ours" else theirs).append(line)
        else:
            out_lines.append(line)
    p.write_text("\n".join(out_lines) + "\n", encoding="utf-8")
    return "<<<<<<<" not in p.read_text(encoding="utf-8")


def attempt_merge(branch: str) -> tuple[bool, list[str]]:
    """Try to merge branch into the current HEAD. Returns
    (success, unresolved_files)."""
    info(f"Merging {branch} ...")
    rc = subprocess.run(
        ["git", "merge", "--no-ff", "--no-edit",
         "-m", f"Merge parallel session {branch} into main", branch],
        cwd=REPO,
    ).returncode
    if rc == 0:
        info(f"  clean merge")
        return True, []

    conflicts = list_conflicts()
    if not conflicts:
        # Merge failed for a reason other than conflicts (e.g. nothing to merge).
        git("merge", "--abort", check=False)
        return False, []
    info(f"  conflicts: {conflicts}")

    # Auto-resolve regenerated files: take ours.
    for path in conflicts:
        if path in REGENERATED_FILES:
            info(f"  auto-resolve (take ours, will regenerate): {path}")
            git("checkout", "--ours", "--", path)
            git("add", "--", path)

    # PROGRESS.md additive merge
    if "PROGRESS.md" in conflicts:
        if auto_resolve_progress_md():
            info("  auto-resolve (additive merge): PROGRESS.md")
            git("add", "--", "PROGRESS.md")
        else:
            warn("  PROGRESS.md additive merge failed")

    # meta/works.yaml status-flip resolution
    if "meta/works.yaml" in conflicts:
        if auto_resolve_works_yaml():
            info("  auto-resolve (drafted wins): meta/works.yaml")
            git("add", "--", "meta/works.yaml")
        else:
            warn("  meta/works.yaml conflict cannot be auto-resolved")

    # Re-check
    remaining = list_conflicts()
    if remaining:
        info(f"  unresolved conflicts remain: {remaining}; aborting merge of {branch}")
        git("merge", "--abort", check=False)
        return False, remaining

    # Complete the merge
    git("commit", "--no-edit")
    info("  merged with auto-resolution")
    return True, []


def regenerate_derived_files() -> bool:
    """Run the regeneration scripts. Returns True if anything changed."""
    scripts = [
        ["build_manifest.py"],
        ["backfill_structural.py"],
        ["enrich_letter_network.py"],
        ["generate_backmatter.py", "--profile", "reading"],
    ]
    for cmd in scripts:
        path = REPO / "scripts" / cmd[0]
        if not path.exists():
            warn(f"missing script: {cmd[0]}; skipping")
            continue
        info(f"running {' '.join(['scripts/' + cmd[0], *cmd[1:]])}")
        rc = subprocess.run(
            [sys.executable, str(path), *cmd[1:]],
            cwd=REPO,
        ).returncode
        if rc != 0:
            warn(f"  {cmd[0]} exited {rc}")

    # Did anything change?
    status = git("status", "--porcelain").stdout.strip()
    return bool(status)


def main() -> int:
    info("Fetching origin ...")
    git("fetch", "origin", "--prune")

    # Make sure we're on main and clean.
    if git("status", "--porcelain").stdout.strip():
        warn("Working tree is not clean. Commit or stash before running.")
        return 1

    info("Resetting local main to origin/main ...")
    # Use checkout -B so this works whether main exists locally or not,
    # and whether the current branch is main, a stale main, or a session
    # branch.
    subprocess.run(
        ["git", "checkout", "-B", "main", "origin/main"],
        cwd=REPO, check=True,
    )

    branches = list_session_branches()
    if not branches:
        info("No stuck session branches. Running post-batch regeneration anyway.")
    else:
        info(f"Found {len(branches)} session branch(es) with unmerged work:")
        for ref, sha in branches:
            info(f"  {ref} @ {sha[:8]}")

    failed: list[tuple[str, list[str]]] = []
    merged: list[str] = []
    for ref, _ in branches:
        ok, conflicts = attempt_merge(ref)
        if ok:
            merged.append(ref)
            info(f"Pushing main after merge of {ref} ...")
            rc = subprocess.run(
                ["git", "push", "origin", "main"], cwd=REPO,
            ).returncode
            if rc != 0:
                warn(f"  push to main failed after merging {ref}; aborting")
                return 1
        else:
            failed.append((ref, conflicts))

    info("Regenerating derived files ...")
    changed = regenerate_derived_files()
    if changed:
        info("Committing post-batch regeneration ...")
        git("add", "-A")
        git(
            "commit", "-m",
            "Post-parallel-batch: regenerate manifest, refresh sidecars",
        )
        rc = subprocess.run(
            ["git", "push", "origin", "main"], cwd=REPO,
        ).returncode
        if rc != 0:
            warn("post-batch push to main failed")
            return 1

    info("Running validator ...")
    rc = subprocess.run(
        [sys.executable, str(REPO / "scripts" / "validate.py")], cwd=REPO,
    ).returncode

    info("=" * 60)
    info(f"Summary:")
    info(f"  Branches merged: {len(merged)}")
    for ref in merged:
        info(f"    {ref}")
    if failed:
        info(f"  Branches that need manual attention: {len(failed)}")
        for ref, conflicts in failed:
            info(f"    {ref}")
            for c in conflicts:
                info(f"      conflict: {c}")
        info("  Resolve those manually and re-run this script, or merge them by hand.")
    if rc != 0:
        warn(f"  Validator exited {rc} -- new errors introduced; investigate.")
        return rc
    info("  Validator clean (warnings ok).")
    info("Done.")
    return 0 if not failed else 1


if __name__ == "__main__":
    raise SystemExit(main())
